services:
  # Frontend Service
  - type: web
    name: fitplan-pro-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://fitplan-pro-backend.onrender.com/api/v1
      - key: NEXT_PUBLIC_APP_NAME
        value: FitPlan Pro
      - key: NEXT_PUBLIC_APP_VERSION
        value: 1.0.0
    healthCheckPath: /
    autoDeploy: true

  # Backend Service
  - type: web
    name: fitplan-pro-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: yarn render:build
    startCommand: yarn render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fitplan-pro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: https://fitplan-pro-frontend.onrender.com
    healthCheckPath: /api/v1/health
    autoDeploy: true

databases:
  - name: fitplan-pro-db
    databaseName: fitplan_pro
    user: fitplan_user
    plan: free
