services:
  - type: web
    name: fitplan-pro-backend
    env: node
    plan: starter
    buildCommand: yarn render:build
    startCommand: yarn render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: fitplan-pro-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /api/v1/health

databases:
  - name: fitplan-pro-db
    databaseName: fitplan_pro
    user: fitplan_user
    plan: starter
